# .github/workflows/daily-rsi.yml
name: Daily RSI Update

on:
  schedule:
    # Run every day at 2:40 PM Sri Lanka time (09:10 AM UTC)
    - cron: '10 09 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-rsi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run RSI scraper
      run: |
        python daily_rsi_scraper.py
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html latest_rsi.json rsi_data_*.json
        git diff --staged --quiet || git commit -m "📊 Daily RSI update - $(date +'%Y-%m-%d')"
        git push
